name: Callee Job
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo The username is ${{ inputs.username }}