name: Download the latest artifacts with artifact name. You need to add a secret with the name "ANCIENT_BLOG_PAT".
on:
  workflow_call:
    inputs:
      YOUR_OWNER:
        description: 'Your owner'
        default: 'ancient-blog'
        required: false
        type: string
      YOUR_REPO:
        description: 'Your repository'
        default: 'hugo.github.io'
        required: false
        type: string
      YOUR_ARTIFACT_NAME:
        description: 'Your Artifact name'
        default: 'voicevox-data'
        required: false
        type: string
    secrets:
      YOUR_PAT:
        description: 'A personal access token from the caller workflow'
        required: false



env:
  YOUR_OWNER: ${{ inputs.YOUR_OWNER }}
  YOUR_REPO: ${{ inputs.YOUR_REPO }}
  YOUR_ARTIFACT_NAME: ${{ inputs.YOUR_ARTIFACT_NAME }}
  YOUR_PAT: ${{ secrets.YOUR_PAT}}


jobs:
  download_latest_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq -y
      - name: Get Artifacts using the GitHub API
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${YOUR_PAT}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${YOUR_OWNER}/${YOUR_REPO}/actions/artifacts \
            -o artifacts.json
          # GitHub APIからarchive_download_urlを取得し、日付でソートして最新のアーティファクトを取得
          result=$(cat artifacts.json | jq -r '.artifacts[] | select(.name == "'"${YOUR_ARTIFACT_NAME}"'")')
          echo "$result"
          archive_download_url=$(cat artifacts.json | jq -r '.artifacts | select(.name == "'"${YOUR_ARTIFACT_NAME}"'") | sort_by(.created_at | tostring) | reverse | .[0].archive_download_url')
          echo ${archive_download_url}
          if [ -z "$archive_download_url" ]; then
            echo "No matching artifacts found for ${YOUR_ARTIFACT_NAME}"
            exit 1
          fi
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${YOUR_PAT}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${archive_download_url} \
            -o artifacts.zip
        continue-on-error: true  # 初回で成果物がない場合エラーを許可します