name: PlantUML to Image

on:
  workflow_call:



# Default to bash
defaults:
  run:
    shell: bash

jobs:

  # plantuml job
  generate_plantuml:
    runs-on: ubuntu-latest
    env:
      PLANT_UML_PATH: content/plantuml
      IMGES_PATH: content/images/platuml
    steps:
      - name: Generate PlantUML Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tpng  ${PLANT_UML_PATH}/*.puml
      - name: Create Destination Folder
        run: mkdir -p ${IMGES_PATH}  # フォルダを作成  
      - name: Move Images
        run: |
          cp ${PLANT_UML_PATH}/*.png ${IMGES_PATH}/
          rm ${PLANT_UML_PATH}/*.png 
