name: Download the latest audio artifacts for test 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["topic/#20"]

jobs:
  test:
  - name: Trigger Child Workflow
    uses: ./.github/workflows/download-latest-artifact.yml
    with:
      workflow: download-latest-artifact
      inputs: |
        YOUR_PAT: ${{ secrets.ANCIENT_BLOG_PAT}}
        YOUR_OWNER: ancient-blog
        YOUR_REPO: hugo.github.io
        YOUR_ARTIFACT_NAME: plant-uml-image
