name: Container Tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["topic/#17"]
jobs:
  test:
    runs-on: ubuntu-latest  # テストランナーをUbuntuで実行
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # コードをチェックアウト
      # Docker Set Up
      - name: Docker Set Up
        # Docker Composeを使用してコンテナをバックグラウンドで起動します。
        run: |
          docker-compose \
          up -d \
          --build
      - name: Check Docker containers running
        run: |
          docker ps -a
          echo "================================="
          docker-compose ps
          echo "================================="
          ifconfig
          echo "================================="
          docker network ls
          echo "================================="
          docker inspect -f '{{.NetworkSettings.Networks}}' voicevox-cpu-latest
          echo "================================="
          ping -c 3 172.81.0.3

      - name: Pre-test
        run: |
          echo -n 'おはようございます。こんにちは。こんばんは。車' > text.txt
          cat text.txt
      - name: Create query.json 
        run: |
          curl -v \
            -X POST \
            "172.81.0.3:50021/audio_query?speaker=1" \
            --get --data-urlencode text@text.txt \
            > query.json      
          cat query.json | grep -o -E "\"kana\":\".*\""
      - name: Create audio.wav
        run: |
          curl -s \
            -H "Content-Type: application/json" \
            -X POST \
            -d @newquery.json \
            "172.81.0.3:50021/synthesis?speaker=1" \
            > audio.wav
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: voicevox-data
          path: |
            ${{ github.workspace }}/*.wav
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      - name: Stop Docker container
        run: |
          docker-compose down
