name: Container Tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["topic/#17"]
jobs:

  pre-test:
    runs-on: ubuntu-latest
    env:
      ARTIFACT: artifact
      YOUR_PAT: ${{ secrets.ANCIENT_BLOG_PAT}}
      YOUR_OWNER: ancient-blog
      YOUR_REPO: hugo.github.io
      YOUR_ARTIFACT_NAME: voicevox-data
      VOICEVOX_PATH: content/voicevox
    steps:
      - name: Get Artifacts using the GitHub API
        run: |
          curl -L \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${YOUR_PAT}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${YOUR_OWNER}/${YOUR_REPO}/actions/artifacts" > artifacts.json

          # JSONデータを解析し、nameで検索して一致する最新のrepository_idを取得
          const data = require('./artifacts.json');
          const searchName = '${YOUR_ARTIFACT_NAME}';

          const matchingArtifacts = data.artifacts.filter(artifact => artifact.name === searchName);

          if (matchingArtifacts.length > 0) {
            const latestArtifact = matchingArtifacts.reduce((prev, current) => (
              new Date(current.updated_at) > new Date(prev.updated_at) ? current : prev
            ));

            const repositoryId = latestArtifact.workflow_run.repository_id;
            console.log(`Repository ID for ${searchName}: ${repositoryId}`);
            const archivedownloadurl = latestArtifact.workflow_run.archive_download_url;
            console.log(`Repository ID for ${searchName}: ${rarchivedownloadurl}`);
            
            // アーティファクトをダウンロード
            curl -L \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${YOUR_PAT}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -o artifacts.zip \
              "https://api.github.com/repos/${YOUR_OWNER}/${YOUR_REPO}/actions/artifacts/${repositoryId}/zip"
          } else {
            console.log(`No matching artifacts found for ${searchName}`);
          }
          ls -lh
        continue-on-error: true  # 初回で成果物がない場合エラーを許可します
      - name: Unzip Artifact
        run: |
          if [ -f artifacts.zip ]; then
            unzip artifacts.zip -d ${ARTIFACT}
          else
            echo "artifacts.zip not found, skipping unzip."
          fi
      - name: Display structure of downloaded files
        run: ls -l
        working-directory: ${{ github.workspace }}/artifact/

  call-voicevosx-workflow:
    needs: pre-test
    uses: ./.github/workflows/voicevosx.yml

  test:
    runs-on: ubuntu-latest
    needs: call-voicevosx-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/content/voicevox/
          name: voicevox-data 
      - name: Display structure of downloaded files
        run: ls -l
        working-directory: ${{ github.workspace }}/content/voicevox/
    
