name: Download the latest audio artifacts for test 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["topic/#20"]

jobs:
  test:
    uses: ./.github/workflows/download-latest-artifact.yml
    with:
      YOUR_OWNER: ancient-blog
      YOUR_REPO: hugo.github.io
      YOUR_ARTIFACT_NAME: voicevox-data
    secrets:
      YOUR_PAT: "${{ secrets.ANCIENT_BLOG_PAT}}"

  composite_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        uses: ./.github/workflows/test
        with:
          MY_MESSAGE: "topic/#20"
        secrets:
          YOUR_PAT: "${{ secrets.ANCIENT_BLOG_PAT}}"
#      - uses: ancient-blog/hugo.github.io@topic/#20



