name: PlantUML to Image and Artifact

on:
  push:
    paths:
      - '.github/workflows/plantuml.yml'
      - 'content/plantuml/*.puml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PLANT_UML_PATH: content/plantuml
  IMGES_PATH: content/images
  ARTIFACT: artifact

# Default to bash
defaults:
  run:
    shell: bash

jobs:

  call-workflow:
    uses: ./.github/workflows/plantuml.yml
  
  test:
    runs-on: ubuntu-latest
    needs: ./.github/workflows/plantuml.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/content/images/plantuml/
          name: plant-uml-image 
      - name: Display structure of downloaded files
        run: ls -l
        working-directory: ${{ github.workspace }}/content/images/plantuml/