name: Download the latest audio artifacts for test 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["topic/#20"]

jobs:
  test:
    uses: ./.github/workflows/download-latest-artifact.yml
    with:
      YOUR_OWNER: ancient-blog
      YOUR_REPO: hugo.github.io
      YOUR_ARTIFACT_NAME: voicevox-data
    secrets:
      YOUR_PAT: "${{ secrets.ANCIENT_BLOG_PAT}}"

  step_test:
    steps:
      - name: download latest artifact
        uses: ./.github/workflows/download-latest-artifact.yml
        with:
          YOUR_OWNER: ancient-blog
          YOUR_REPO: hugo.github.io
          YOUR_ARTIFACT_NAME: voicevox-data
        secrets:
          YOUR_PAT: "${{ secrets.ANCIENT_BLOG_PAT}}"
      - name: test


