name: Voicevox Audio Generator

on:
  workflow_call:

env:
  ARTIFACT: artifact
  VOICEVOX_PATH: content/voicevox
  DOCKER_BUILDKIT: 1  # Dockerビルドキットを有効にする

jobs:
  generate_voicevox_audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for File Changes
        id: file_changes
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) =~ ^content/voicevox/.*\.txt$ ]]; then
            echo "Text files have changed, triggering the script."
            echo "trigger=true" >> $GITHUB_ENV  # 環境ファイルに変数を設定
          else
            echo "No changes in text files, skipping the script."
            echo "trigger=false" >> $GITHUB_ENV  # 環境ファイルに変数を設定
          fi

      - name: Docker Set Up
        if: env.trigger == 'true'
        run: |
          docker-compose up -d --build
          docker ps -a
          docker-compose ps
          ping -c 3 172.81.0.3

      - name: Download artifact
        if: env.trigger == 'true'
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifact
          name: voicevox-data 

      - name: Create Destination Folder
        if: env.trigger == 'true'
        run: |
          if [ ! -d "${ARTIFACT}" ]; then
            mkdir -p "${ARTIFACT}"
          else
            echo "Folder ${ARTIFACT} already exists."
          fi
      - name: Prepare a Shell Script
        if: env.trigger == 'true'
        run: |
          mv ./content/voicevox/voicevox.sh .
          chmod +x voicevox.sh

      - name: Run the Shell Script
        if: env.trigger == 'true'
        run: |
          ./voicevox.sh
          ls -l

      - name: Copy Files
        if: env.trigger == 'true'
        run: |
          cp ${{ github.workspace }}/${VOICEVOX_PATH}/*.wav ${ARTIFACT}/

      - name: Upload Artifact
        if: env.trigger == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: voicevox-data
          path: |
            ${{ github.workspace }}/artifact
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`