name: Voicevox Audio Generator

on:
  workflow_call:
  push:
    paths:
      - 'content/voicevox/*.txt'
env:
  ARTIFACT: artifact
  VOICEVOX_PATH: content/voicevox
  YOUR_PAT: ${{ secrets.ANCIENT_BLOG_PAT}}
  YOUR_OWNER: ancient-blog
  YOUR_REPO: hugo.github.io
  YOUR_ARTIFACT_NAME: voicevox-data
  DOCKER_BUILDKIT: 1  # Dockerビルドキットを有効にする

jobs:
  generate_voicevox_audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: download latest voicevox-data of artifact
        uses: ./.github/workflows/download-latest-artifact
        with:
          owner: ancient-blog
          repo: hugo.github.io
          name: voicevox-data
          token: "${{ secrets.ANCIENT_BLOG_PAT }}"
          path: |
            "${{ github.workspace }}/${ARTIFACT}"

      - name: Docker Set Up
        run: |
          docker-compose up -d --build
          docker ps -a
          docker-compose ps
          ping -c 3 172.81.0.3

      - name: Create Destination Folder
        run: |
          if [ ! -d "${ARTIFACT}" ]; then
            mkdir -p "${ARTIFACT}"
          fi

      - name: Generate Audio
        run: |
          changed_files=$(git log --stat -1 --pretty=format:"" | grep -o -E 'content/voicevox/[^/]+\.txt')
          echo "変更されたファイル:"
          echo "$changed_files"

          for filename in $changed_files
          do
            # jsonファイルの作成
            curl -s \
              -X POST \
              "localhost:50021/audio_query?speaker=3" \
              --get --data-urlencode text@"$filename" \
              -o query.json
            echo "Created query.json for $filename"
    
            cat query.json | grep -o -E "\"kana\":\".*\"" | xargs -I {} echo {}
    
            # wavファイルの作成
            curl -s \
              -H "Content-Type: application/json" \
              -X POST \
              -d @query.json \
              "localhost:50021/synthesis?speaker=3" \
              -o audio.wav   
            # 拡張子.txtを削除して新しい変数に格納
            filename_without_extension=$(echo "$filename" | sed 's/\.txt$//')

            # wavファイルのリネーム
            mv audio.wav "${filename_without_extension}.wav"

            echo "Renamed audio.wav to ${filename_without_extension}.wav"

            echo "Finished processing $filename"
          done

      - name: Copy Files
        run: |
          if [ -n "$(find "${{ github.workspace }}/${VOICEVOX_PATH}" -maxdepth 1 -type f -name '*.wav')" ]; then
            cp "${{ github.workspace }}/${VOICEVOX_PATH}"/*.wav "${ARTIFACT}/"
          else
            echo "No .wav files found. Skipping copy."
          fi
          ls ${ARTIFACT} -lh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: voicevox-data
          path: |
            ${{ github.workspace }}/artifact
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`