name: Voicevox Audio Generator

on:
  workflow_call:

env:
  ARTIFACT: artifact
  VOICEVOX_PATH: content/voicevox
  DOCKER_BUILDKIT: 1  # Dockerビルドキットを有効にする

jobs:
  generate_voicevox_audio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Set Up
        run: |
          docker-compose up -d --build
          docker ps -a
          docker-compose ps
          ping -c 3 172.81.0.3

      - name: Create Destination Folder
        run: |
          if [ ! -d "${ARTIFACT}" ]; then
            mkdir -p "${ARTIFACT}"
          fi

      - name: Prepare a Shell Script
        run: |
          mv ./content/voicevox/voicevox.sh .
          chmod +x voicevox.sh

      - name: Run the Shell Script
        run: |
          ./voicevox.sh
          ls -l

      - name: Copy Files
        run: |
          if [ -n "$(find "${{ github.workspace }}/${VOICEVOX_PATH}" -maxdepth 1 -type f -name '*.wav')" ]; then
            cp "${{ github.workspace }}/${VOICEVOX_PATH}"/*.wav "${ARTIFACT}/"
          else
            echo "No .wav files found. Skipping copy."
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: voicevox-data
          path: |
            ${{ github.workspace }}/artifact
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`